name: Release

on: 
  push:
    branches: 
      - lk/semantic-workflow

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        node-version: [16]
        toxenv: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install pip Dependencies
        run: pip install -r requirements/pip.txt

      - name: Install CI Dependencies
        run: pip install -r requirements/ci.txt

      - name: Install GNU gettext
        run: sudo apt-get install gettext

      - name: Install Node Dependencies
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

      - name: Build python package
        run: python setup.py sdist bdist_wheel

      - name: Release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: npx semantic-release